== Zen of Xen

=== Power of Name

If you are a fan of fantasy books, you know that a name has power.
Let us find out what name Xen means.
Xen was originally developed as virtual machine monitor for XenoServers project.
Word _xeno_ (/'zeno) originates from Greek word xenos,
meaning "alien, stranger, foreigner".
Therefore the name Xen is hinting at advanced alien technology.

Word Xen is often combined with word "hypervisor",
because Xen virtual machine monitor is a hypervisor.
Prefix _hyper_ here means "super-duper". 
OS kernel runs at elevated privilege level compare to applications
and is called _supervisor_ because it a) manages the applications
and b) has more priviledges than application code.
When OS kernel runs under control of Xen virtual machine monitor,
the kernal is supervised by the Xen, and Xen has higher privilege level.
The fact that Xen runs at higher privilege level than "supervisor mode" OS code
and supervises it is the origin of the term "hypervisor".

Sometimes word Xen is used just for the hypervisor,
other times it is used for all the parts involved in to
the virtualization solution:
hypervisor, OS kernel virtualization modifications,
drivers for paravirtualization, tools and etc.

=== What Is Virtualization?

Xen virtualizes the computing system as whole,
including CPU, memory, storage devices, network resources, I/O devices and etc.
The virtualization in this case is the act of creating a virtual
(rather than actual) version of a computer hardware platform.
Normally, in order to get most benifits from the virtualization,
more than one virtual hardware platform is created.
The case when a single virtual platform is created
can be considered an emulation (and it is also has its usages).

=== Hypervisor-based approach to virtualization

There are many different approaches to virtualization,
we are not going to discuss and compare them here;
if you are interested in this topic,
there are many available books and Internet resources that explain
different virtualization techniques.
Xen is using hypervisor-based approach, where a hypervisor
is a low-level virtual machine monitor that runs directly
on the physical hardware and loads first during the machine
boot process.
The hypervisor runs virtual machines (VM).
Virtual machine runs operating system (which runs applications).
Normally, an operating system is compiled for the same instruction set
as the physical machine on which the virtual systems are running.

[ditaa]
....
+------------------------------------------------+
|                                                |
| +--------------------------------------------+ |
| |                                            | |
| | +----------+  +----------+  +----------+   | |
| | | Virtual  |  | Virtual  |  | Virtual  |   | |
| | | Machine  |  | Machine  |  | Machine  |   | |
| | |  with    |  |  with    |  |  with    |   | |
| | | Admini-  |  | Guest OS |  | Guest OS |   | |
| | | strative |  |          |  |          |   | |
| | | Control  |  +----------+  +----------+   | |
| | |          |     domU          domU        | |
| | |          |                               | |
| | +----------+                               | |
| |    dom0                                    | |
| |                 Hypervisor                 | |
| | cPNK                                       | |
| +--------------------------------------------+ |
|                                                |
|                    Hardware                    |
| cBLU                                           |
+------------------------------------------------+
....

Xen terminology defines a concept of "Xen domain", which is
a specific instance of a Xen virtual machine.
Xen supports two basic types of domains:

* Xen architecture has one domain with a specially privileged
  Xen-modified kernel that is used to manage, monitor, and administer all
  other Xen virtual machines. This specially priviliged domain and
  kernel is known as _domain0_ or _dom0_.
  This kernel communicates with the hypervisor.
* Other domains are known as guest domains, unprivileged domains,
  _domainU_ or _domU_.
  It is _dom0_ that starts any _domU_.

=== CPU Virtualization

=== I/O Virtualization

=== History of Pitfalls due to CPU arhitecture

While designing a new CPU the architects should be aware of the problems other CPU architectures
had or still have to support virtualization by Xen.
The understading of past and existing problems is crutial in designing
a CPU that can support virtualization efficiently, when overhead of running
the hypervisor is practically unnoticeable.

* One well known problem with x86 was that some privileged instructions did not
  trap when they were executed with unsufficient privileges failing silently.
  Some virtualizers monitored instruction stream and patched those misbehaving
  instructions, practically performing binary translation, which caused
  significant degradation of performance.
* In case of paravirtualization, an absense of a special instructions in the ISA
  to be used for fast hypecall to the hypervisor is very critical for the performance.
* It used to be on x86 that booting 32-bit domain0 dictated all other domainU kernels
  to be 32-bit, similar for 64-bit domain0.
  New CPU architecture should allow different meaningful combinations of kernels, including
  bitness and endianess.
* TODO IOMMU
* TODO Need to use QEMU for full system virtualization FVM

=== CPU and system support for virtualization

.Required functinality
* Ability to bind a virtual machine to a specific CPU on the host system.
  It helps to solve performance problems of a virtual machine under heavy load.
* No limitation for the size of virtual address space available for OS kernels
  running inside virtual machine.
* Each guest OS may create high network traffic, multiple guests can easily
  overload the capabilities of a single network interface.
  The system must support multiple network interfaces with high bandwidth.
* The system must support high IO traffic as guests may run storage intensive
  applications, such as database applications.
* The system must satisfy all requirements of Trusted Computing for the virtualized
  environment when multiple operating systems are simultaneously running on
  a single platform (with a single TPM device).
  Including the secure migration of the TPM state from one physical system
  to another when domainU guests are migrated from one system to another.