== Devices

=== PV devices

Devices such as network and disk are exported to guests using a splitd evice driver.
The device driver domain (usually dom0), which accesses the physical device
directly also runs a backend driver, serving requests to that device from guests.
Each guest will use a simple frontend driver, to access the backend.
Communication between these domains is composed of two parts:
First, data is placed on to a shared memory page between the domains.
Second, an event channel between the two domains is used to pass notification
that data is outstanding. This separation of notification from data transfer
allows message batching, and results in very efficient device access.

Event channels are used extensively in device virtualization;
each domain has a number of end-points or _ports_ each of which
may be bound to one of the following _event sources_:

- a physical interrrupt from a real device,
- a virtual interrupts (callback) from Xen hypervisor, or
- a signal from another domain.

Events are lightweight and do not carry much information beyond
the source of the notification.
Hence when performing bulk data transfer, events are typically used
as synchronization primitives over a shared memory transport.
Event channels are managed via the `event_channel_op()` hypercall.

=== PV split-driver

TODO

=== PV Network I/O

Virtual network device services are provided by shared memory communication
with a backend domain. From the point of view of other domains,
the backend may be viewed as a virtual ethernet switch element 
with each domain having one or more virtual network interfaces connected to it.

==== Backend packet handling

The backend driver is responsible for a variety of actions relating to the transmission and 
reception of packets from the physical device.
With regard to transmission, the backend performs these key actions:

Validation:: To ensure that domains do not attempt to generate invalid traffic,
the backend driver may validate headers ensuring that source MAC and IP addresses
match the interface that they have been sent from.

Scheduling:: Since a number of domains can share a single physical network interface,
the backend must mediate access when several domains each have packets queued
for transmission. This general scheduling function subsumes basic shaping
or rate-limiting schemes.

Logging and Accounting:: The backend domain can be configured with classifier rules 
that control how packets are accounted or logged.

Demultiplexing on receipt:: On receipt of incoming packets, the backend acts as a
simple demultiplexer: Packets are passed to the appropriate virtual interface after any 
necessary logging and accounting have been carried out.


==== Data transfer

Each virtual interface uses two "descriptor rings", one for transmit,the other for receive.
Each descriptor identifies a block of contiguous physical memory allocated to the domain.

The transmit ring carries packets to transmit from the guest to the backend domain.
The return path of the transmit ring carries messages indicating that the contents have been 
physically transmitted and the backend no longer requires the associated pages of memory.

To receive packets,the guest places descriptors of unused pages on the receive ring.
The backend will return received packets by exchanging these pages in the domain's memory 
with new pages containing the received data, and passing back descriptors regarding
the new packets on the ring. This zero-copy approach allows the backend to maintain
a pool of free pages to receive packets into, and then deliver them to appropriate
domains after examining their headers.

If a domain does not keep its receive ring stocked with empty buffers then packets
destined to it may be dropped. This provides some defence against receive
livelock problems because an overload domain will cease to receive
further data. Similarly, on the transmit path, it provides the application with
feedback on the rate at which packets are able to leave the system.

Flow control on rings is achieved by including a pair of producer indexes
on the shared ring page. Each side will maintain a private consumer index
indicating the next outstanding message. In this manner, the domains cooperate
to divide the ring into two message lists, one in each direction.
Notification is decoupled from the immediate placement of new messages on the ring;
the event channel will be used to generate notification when either a certain number
of outstanding messages are queued, or a specified number of nanoseconds have
elapsed since the oldest message was placed on the ring.

=== PV Block I/O


=== PV PCI

Guest operating systems should not attempt to determine the PCI
configuration directly by accessing the PCI BIOS.
Instead, they should use Xen hypercall `physdev_op(void *physdev_op)`
to perform PCI configuration; it can be PCI config read, write and so on.